### ISSUE TITLE
Fix this bug w/ white text on white background! 

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/coderwall#1]
![capturfiles_3](https://cloud.githubusercontent.com/assets/1480063/7508374/022eea6c-f434-11e4-99b8-b44c22606a38.png)

A very naive fix is this CSS hack:

```css
.jq-dropdown-panel{
    background-color: #343131;
}
```

Which looks like this:

![capturfiles_4](https://cloud.githubusercontent.com/assets/1480063/7508391/3ea68dd8-f434-11e4-8ba8-f59986fbfb07.png)
